print("Welcome to the calculator!")
print("Please select an operation:")
print("1. Add")
print("2. Subtract")
print("3. Multiply")
print("4. Divide")
print("5. Square")
print("6. Cube")
print("7. Square root")
print("8. Power")
print("0. Exit")
print("Enter your choice:")